### ISSUE TITLE
Merge request

### ISSUE THREAD

**Issue by Laski** [somodi/tp2#1]
Hacemos un merge de este repo con los otros dos y tenemos un único repo de orga2 para el histórico? (como deberíamos haber hecho desde el principio)

**Comment by somodi** [comment]
Sí. ¿Lo hacés? No sé cómo se hace...
:=)

**Comment by Laski** [comment]
Pasé este a https://github.com/somodi/tp3, podés borrar este y cambiar el nombre de tp3 a orga2.
El TP1 era individual así que lo dejé separado, yo también tengo un repo para ese.
